<a href="https://colab.research.google.com/github/Nischay18/ENSYS5800-AI-Energy-somu.n/blob/main/02.%20Fundamentals%20-%20Data%20Analytics/02a.%20Fundamentals%20-%20Descriptive%20Analytics%20-%20Introduction%20to%20Python%20(Example%202.1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ENSYS 5800: Applications of Artificial Intelligence in Energy Systems

# 02a. Fundamentals - Descriptive Analytics

## Overview of Python

#### Working with data types in Python

*References:*  
* https://wiki.python.org/moin/BeginnersGuide/Overview
* https://docs.python.org/3/tutorial/datastructures.html#

In [ ]:
x = 1 # Assign the number, 1, to the variable x

In [ ]:
print(x)  # show the value of x in the user interface

1


In [ ]:
y = 2*x + 4 # specify an equation that shows the dependency of y on the independent variable x
print(y) # evaluate and show the value of y in the user interface, for the current value of x

6


*Python data types include* **numbers (floating point, complex, and integers)**, **arrays**, **strings**, **lists**, and **dictionaries**

In [ ]:
xnum = 0.01       # Floating point number with two significant digits
xint = 1          # Integer
xstr = "string"   # String (non-numeric variable) is a group of characters
print(xstr)

string


*Working with arrays: An **array** is a vector of homogeneous items (ex. an array of numbers)*

In [ ]:
import array                       # The import command is how you bring a python package into your computing space
xarr = array.array('i',[0, 1, 2])  # An array is a vector of homogeneous items (ex. an array of numbers)
print(xarr[0])                     # Print the first item in the array (notice that the first item starts with 0)

0


*Working with Lists: A **List** is a group of items that can be heterogeneous (ex. strings, numbers, arrays, etc.). You can do much more with lists than arrays*

In [ ]:
xlist = [2,"string"]               # Assign a number and a string to a list
print(xlist)                       # Print the entire list
print(xlist[1])                    # Print item 2 in the list

[2, 'string']
string


In [ ]:
xlist = [2,"string",[1,2]]         # Assign a number, a string, and an array to a list
                                   # Unlike an array, you do not need to explicitly declare it
print(xlist)                       # Print the entire list
print(xlist[2])                    # Print item 3 in the list
print(xlist[2][1])                 # Print the second array item for item 3 in the list

[2, 'string', [1, 2]]
[1, 2]
2


In [ ]:
xlist.append(3)                    # You can easily append a new item to the list, using a built in function for a list type
print(xlist)

[2, 'string', [1, 2], 3]


In [ ]:
type(xlist[0])                     # Determine the type of an item in a list (this item is an integer, int)

int

In [ ]:
type(xlist[1])                     # Determine the type of an item in a list (this item is a string, str)

str

*Working with Sets: A **Set** is an unordered group of unique items (ex. colors 'red','orange',etc.). You can do much more with lists than arrays*

In [ ]:
xset = {'red','blue','orange'}     # You create a set by using {}, with the items separated by commas
print(xset)

{'orange', 'red', 'blue'}


In [ ]:
'blue' in xset                     # You can use built in functions. This example shows how you can easily check to see if 'blue' is in the set *xset**

True

In [ ]:
xset = set({'red','red','blue','orange'})  # Set must be unique. The Set command automatically finds the unique items
print(xset)

{'orange', 'red', 'blue'}


*Working with Dictionaries: A* **Dictionary** *is a sequence that is indexed by* **keys**

In [ ]:
xdict = {'red': 1, 'blue': 2}      # You define a dictionary similar to a set, but must add the associated values to each key
print(xdict)                       # Print the full dictionary
print(xdict['red'])                # Determine the value associated with the 'red' key

{'red': 1, 'blue': 2}
1


### Scientific Computing with Python (Numpy Package)

*References:*  
    
* http://www.numpy.org/
* [Python Data Science Handbook by Jake VanderPlas](https://www.oreilly.com/library/view/python-data-science/9781491912126/)
* [Colab Notebook for 'Python Data Science Handbook'](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb#scrollTo=rRb4rMNoRbvz)

**Numpy** *is a python programming library that is focused on working with large data sets (arrays and matrices) and includes numerous math functions for operating on data sets*
>[Python Data Science Handbook: Introduction to NumPy](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.00-Introduction-to-NumPy.ipynb#scrollTo=mEY3h_qNR-nT)

Note that Numpy is very powerful for mathematical computations, where the fundamental items are numeric (similar to an array)

In [ ]:
import numpy as np                # When importing library packages, you should include the 'as x' statement to differentiate from other packages
xnparr = np.array([0, 1, 2])      # An example of defining an array using Numpy
print(xnparr)                     # Print the full Numpy array
print(xnparr[0])                  # Print the 1st item in the Numpy array

[0 1 2]
0


You can use built in Numpy functions to quickly create arrays for calculations

In [ ]:
np.zeros(3)                       # Create an array of 3 zeros

array([0., 0., 0.])

In [ ]:
np.eye(3)                         # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linspace(0,10,5)               # Create a linearly increasing array, starting with 0, ending with 10, with 5 items

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.array([[ 1,  2, 3],            # Specify a 2x2 array (i.e. matrix)
       [ -3,  0,  0],
       [ -1,  0,  1]])

array([[ 1,  2,  3],
       [-3,  0,  0],
       [-1,  0,  1]])

Assign Numpy arrays to variables

In [ ]:
xnparray = np.array([[ 1,  2, 3],            # Assign a 2x2 array (i.e. matrix) to the variable xnparray
       [ -3,  0,  0],
       [ -1,  0,  1]])
print(xnparray)

[[ 1  2  3]
 [-3  0  0]
 [-1  0  1]]


In [ ]:
print("Shape is ",xnparray.shape)                # Print the shape of the array
print("Size is ",xnparray.size)                  # Print the size of the array
print("# of dimensions is ",xnparray.ndim)       # Print the number of dimensions of the array

Shape is  (3, 3)
Size is  9
# of dimensions is  2


Use indexing to select an item (similar to regular Python arrays)

In [ ]:
xnparray[0][1]                                   # Print the item in the 1st row and 2nd column of the array

2

In [ ]:
xnparray[-1][-1]                                 # Print the item in the last row and last column

1

In [ ]:
xnparray[1,:]                                    # Slice an array using :  (ex. show the second row)

array([-3,  0,  0])

In [ ]:
xnparray[:,1]                                    # Slice an array using :  (ex. show the second column)

array([2, 0, 0])

In [ ]:
xnparray[1,:] = 1                                # Reassign values across an array (ex. set row 2 to the value 1)
print(xnparray)

[[ 1  2  3]
 [ 1  1  1]
 [-1  0  1]]


In [ ]:
xnparray.reshape(9,1)                            # Reshape the array to a 9x1 array

array([[ 1],
       [ 2],
       [ 3],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 0],
       [ 1]])

In [ ]:
xnparray/2                                       # Math is easy with Numpy (each item is divided by 2)

array([[ 0.5,  1. ,  1.5],
       [ 0.5,  0.5,  0.5],
       [-0.5,  0. ,  0.5]])

## Overview of Python Pandas Dataframe

**Pandas** *is a large python library dedicated to performance data analysis and transformations, which combines numerical and database capabilities into one package*
*Many data scientists spend a large portion of time using the Pandas library. It is arguably one of the most widely and commonly used Python libraries.*
> *References*
> * https://pandas.pydata.org/
> * [Python Data Science Handbook: Introduction to Pandas](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/03.00-Introduction-to-Pandas.ipynb)

*Pandas builds upon the previous data types (ex. Numpy) by creating what is called a* **data structure** *type. Data structures are abstract groupings and mappings for multiple items.
Think of a data structure as a more generalized type of list. And, the specific data structure object, in python, is called a* **dataframe**. *Pandas Dataframes are very powerful data analysis objects. And, the Pandas library allows you to perform countless operations on this relatonal and labeled data.*

#### Example 2.1: Solar PV System Performance - Importing and Inspecting the Data

![Example2.1_data_import_inspection.png](attachment:06bba1c2-4227-40b4-ac1a-70a8878fef75.png)

In [ ]:
import pandas as pd                             # Import the pandas library as the object named 'pd'

url="https://storage.googleapis.com/nrel-datahub/NREL_DataHub_PVDAQ"    # Assign the data source URL as a variable called 'url'
data=pd.read_csv(url, sep=',', header=None, error_bad_lines=False)      # Create pandas dataframe, pd, by reading the url data as a csv formatted data file

b'Skipping line 8500: expected 7 fields, saw 117\nSkipping line 8863: expected 7 fields, saw 32\nSkipping line 13537: expected 7 fields, saw 2737\nSkipping line 13542: expected 7 fields, saw 12\nSkipping line 34453: expected 7 fields, saw 27\nSkipping line 34509: expected 7 fields, saw 27\nSkipping line 50945: expected 7 fields, saw 20342\nSkipping line 53304: expected 7 fields, saw 27\nSkipping line 53587: expected 7 fields, saw 17\nSkipping line 53763: expected 7 fields, saw 27\nSkipping line 67878: expected 7 fields, saw 27\nSkipping line 67919: expected 7 fields, saw 27\nSkipping line 70203: expected 7 fields, saw 27\nSkipping line 71144: expected 7 fields, saw 1642\nSkipping line 104953: expected 7 fields, saw 11282\nSkipping line 105737: expected 7 fields, saw 92\nSkipping line 115698: expected 7 fields, saw 22\nSkipping line 116707: expected 7 fields, saw 32\nSkipping line 116713: expected 7 fields, saw 37\nSkipping line 119348: expected 7 fields, saw 52\n'
b'Skipping line 13623

In [ ]:
help(pd.read_csv)                               # How to open a help section on a specific built-in function (this is the help for the read_csv function)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer: Union[ForwardRef('PathLike[str]'), str, IO[~T], io.RawIOBase, io.BufferedIOBase, io.TextIOBase, _io.TextIOWrapper, mmap.mmap], sep=<object object at 0x000001E2C6D77860>, delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal: str = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, error_bad_lines=True, warn_bad_lines=True, delim_

*View the properties of the raw data variable (which is a 'dataframe')*

In [ ]:
data.head()                                     # View the top and bottom rows

ac_power  poa_irradiance  ambient_temp  wind_speed  \
Datetime                                                                  
2010-02-25 14:16:00    62.464           96.55         4.017       0.564   
2010-02-25 14:17:00    84.915          103.57         3.990       1.004   
2010-02-25 14:18:00    94.197          108.96         3.926       1.459   
2010-02-25 14:19:00    27.059          115.05         3.854       1.326   
2010-02-25 14:20:00    79.618          127.72         3.792       1.899   

                     soiling  
Datetime                      
2010-02-25 14:16:00      1.0  
2010-02-25 14:17:00      1.0  
2010-02-25 14:18:00      1.0  
2010-02-25 14:19:00      1.0  
2010-02-25 14:20:00      1.0

In [ ]:
data.shape                                      # View the size of the dataframe

(1541277, 5)

In [ ]:
data                                            # View the dataframe as a table, for visual inspection (note that the rows and columns are just numbers)

0  1        2        3      4      5      6
0        2010-02-25 14:16:00  4   62.464   96.550  4.017  0.564  1.000
1        2010-02-25 14:17:00  4   84.915  103.570  3.990  1.004  1.000
2        2010-02-25 14:18:00  4   94.197  108.960  3.926  1.459  1.000
3        2010-02-25 14:19:00  4   27.059  115.050  3.854  1.326  1.000
4        2010-02-25 14:20:00  4   79.618  127.720  3.792  1.899  1.000
...                      ... ..      ...      ...    ...    ...    ...
1541272  2016-12-13 09:53:00  4  701.066  839.505  1.485  2.357  0.992
1541273  2016-12-13 09:54:00  4  713.114  851.519  1.300  2.453  0.992
1541274  2016-12-13 09:55:00  4  712.889  851.149  1.218  1.338  0.992
1541275  2016-12-13 09:56:00  4  714.269  853.730  1.372  0.886  0.992
1541276  2016-12-13 09:57:00  4  221.987  858.830  1.542  1.391  0.992

[1541277 rows x 7 columns]

In [ ]:
data.columns = (['Datetime','system_id','ac_power', 'poa_irradiance',  
                'ambient_temp', 'wind_speed','soiling'])                # Create names for each column
data                                                                    # Note that the columns are now named, but the rows are still just numbers

Datetime  system_id  ac_power  poa_irradiance  \
0        2010-02-25 14:16:00          4    62.464          96.550   
1        2010-02-25 14:17:00          4    84.915         103.570   
2        2010-02-25 14:18:00          4    94.197         108.960   
3        2010-02-25 14:19:00          4    27.059         115.050   
4        2010-02-25 14:20:00          4    79.618         127.720   
...                      ...        ...       ...             ...   
1541272  2016-12-13 09:53:00          4   701.066         839.505   
1541273  2016-12-13 09:54:00          4   713.114         851.519   
1541274  2016-12-13 09:55:00          4   712.889         851.149   
1541275  2016-12-13 09:56:00          4   714.269         853.730   
1541276  2016-12-13 09:57:00          4   221.987         858.830   

         ambient_temp  wind_speed  soiling  
0               4.017       0.564    1.000  
1               3.990       1.004    1.000  
2               3.926       1.459    1.000  
3               3.854       1.326    1.000  
4               3.792       1.899    1.000  
...               ...         ...      ...  
1541272         1.485       2.357    0.992  
1541273         1.300       2.453    0.992  
1541274         1.218       1.338    0.992  
1541275         1.372       0.886    0.992  
1541276         1.542       1.391    0.992  

[1541277 rows x 7 columns]

In [ ]:
data['Datetime'] =  pd.to_datetime(data['Datetime'])                    # Convert the 'Datetime' column to the proper datetime format for time series analysis
data                                                                                                                        

Datetime  system_id  ac_power  poa_irradiance  \
0       2010-02-25 14:16:00          4    62.464          96.550   
1       2010-02-25 14:17:00          4    84.915         103.570   
2       2010-02-25 14:18:00          4    94.197         108.960   
3       2010-02-25 14:19:00          4    27.059         115.050   
4       2010-02-25 14:20:00          4    79.618         127.720   
...                     ...        ...       ...             ...   
1541272 2016-12-13 09:53:00          4   701.066         839.505   
1541273 2016-12-13 09:54:00          4   713.114         851.519   
1541274 2016-12-13 09:55:00          4   712.889         851.149   
1541275 2016-12-13 09:56:00          4   714.269         853.730   
1541276 2016-12-13 09:57:00          4   221.987         858.830   

         ambient_temp  wind_speed  soiling  
0               4.017       0.564    1.000  
1               3.990       1.004    1.000  
2               3.926       1.459    1.000  
3               3.854       1.326    1.000  
4               3.792       1.899    1.000  
...               ...         ...      ...  
1541272         1.485       2.357    0.992  
1541273         1.300       2.453    0.992  
1541274         1.218       1.338    0.992  
1541275         1.372       0.886    0.992  
1541276         1.542       1.391    0.992  

[1541277 rows x 7 columns]

In [ ]:
data = data.set_index(['Datetime'])              # Set the 'Datetime' column as the index (i.e. key) in the pandas dataframe
data                                             # Note that the row names are now the datetime stamps

system_id  ac_power  poa_irradiance  ambient_temp  \
Datetime                                                                 
2010-02-25 14:16:00          4    62.464          96.550         4.017   
2010-02-25 14:17:00          4    84.915         103.570         3.990   
2010-02-25 14:18:00          4    94.197         108.960         3.926   
2010-02-25 14:19:00          4    27.059         115.050         3.854   
2010-02-25 14:20:00          4    79.618         127.720         3.792   
...                        ...       ...             ...           ...   
2016-12-13 09:53:00          4   701.066         839.505         1.485   
2016-12-13 09:54:00          4   713.114         851.519         1.300   
2016-12-13 09:55:00          4   712.889         851.149         1.218   
2016-12-13 09:56:00          4   714.269         853.730         1.372   
2016-12-13 09:57:00          4   221.987         858.830         1.542   

                     wind_speed  soiling  
Datetime                                  
2010-02-25 14:16:00       0.564    1.000  
2010-02-25 14:17:00       1.004    1.000  
2010-02-25 14:18:00       1.459    1.000  
2010-02-25 14:19:00       1.326    1.000  
2010-02-25 14:20:00       1.899    1.000  
...                         ...      ...  
2016-12-13 09:53:00       2.357    0.992  
2016-12-13 09:54:00       2.453    0.992  
2016-12-13 09:55:00       1.338    0.992  
2016-12-13 09:56:00       0.886    0.992  
2016-12-13 09:57:00       1.391    0.992  

[1541277 rows x 6 columns]

In [ ]:
data=data.drop(['system_id'], axis=1)           # Drop the 'system_id' column since we do not need this data for the analysis
data                                            # Print the data table for visual inspection

ac_power  poa_irradiance  ambient_temp  wind_speed  \
Datetime                                                                  
2010-02-25 14:16:00    62.464          96.550         4.017       0.564   
2010-02-25 14:17:00    84.915         103.570         3.990       1.004   
2010-02-25 14:18:00    94.197         108.960         3.926       1.459   
2010-02-25 14:19:00    27.059         115.050         3.854       1.326   
2010-02-25 14:20:00    79.618         127.720         3.792       1.899   
...                       ...             ...           ...         ...   
2016-12-13 09:53:00   701.066         839.505         1.485       2.357   
2016-12-13 09:54:00   713.114         851.519         1.300       2.453   
2016-12-13 09:55:00   712.889         851.149         1.218       1.338   
2016-12-13 09:56:00   714.269         853.730         1.372       0.886   
2016-12-13 09:57:00   221.987         858.830         1.542       1.391   

                     soiling  
Datetime                      
2010-02-25 14:16:00    1.000  
2010-02-25 14:17:00    1.000  
2010-02-25 14:18:00    1.000  
2010-02-25 14:19:00    1.000  
2010-02-25 14:20:00    1.000  
...                      ...  
2016-12-13 09:53:00    0.992  
2016-12-13 09:54:00    0.992  
2016-12-13 09:55:00    0.992  
2016-12-13 09:56:00    0.992  
2016-12-13 09:57:00    0.992  

[1541277 rows x 5 columns]